include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    invalid_annotation_target: ignore
  exclude:
    - lib/generated
    - lib/l10n
    - lib/generated_plugin_registrant.dart
    - "**/*.g.dart"
  # plugins:
  #   - custom_lint

linter:
  rules:
    - camel_case_types
    - camel_case_extensions
    - library_names
    - file_names
    - library_prefixes
    - curly_braces_in_flow_control_structures
    - constant_identifier_names
    - directives_ordering
    - slash_for_doc_comments
    - implementation_imports
    - avoid_relative_lib_imports
    - prefer_relative_imports
    - prefer_adjacent_string_concatenation
    - unnecessary_brace_in_string_interps
    - prefer_iterable_whereType
    - unnecessary_lambdas
    - avoid_init_to_null
    - unnecessary_getters_setters
    - unnecessary_this
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - unnecessary_new
    - unnecessary_const
    - avoid_catching_errors
    - use_rethrow_when_possible
    - prefer_interpolation_to_compose_strings
    - prefer_collection_literals
    - prefer_function_declarations_over_variables
    - use_to_and_as_if_applicable
    - prefer_final_fields
    - avoid_setters_without_getters
    - avoid_private_typedef_functions
    - hash_and_equals
    - avoid_null_checks_in_equality_operators
    - prefer_mixin
    - prefer_generic_function_type_aliases

