name: demo1
description: 典典的小卖部,淘客版本 qq群667186542
version: 3.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  fbutton_nullsafety: ^5.0.0
  fsuper_nullsafety: ^3.0.3
  common_utils: ^2.1.0
  extended_image: ^10.0.1
  waterfall_flow: ^3.1.1
  pull_to_refresh_notification: ^3.1.0
  connectivity_plus: ^6.1.4
  shimmer: ^3.0.0
  flutter_svg: ^2.1.0
  html: ^0.15.6
  after_layout: ^1.2.0
  palette_generator: ^0.3.3+7
  crypto: ^3.0.6
  encrypt: ^5.0.3
  extended_nested_scroll_view: ^6.2.1
  fcontrol_nullsafety: ^2.0.0
  get_it: ^8.0.3
  logger: ^2.5.0
  bubble_tab_indicator: ^0.1.6
  flutter_markdown: ^0.7.7+1
  package_info_plus: ^8.3.0
  fbroadcast_nullsafety: any
  show_up_animation: ^2.1.2
  hive: ^2.2.3
  flutter_swiper_null_safety_flutter3: ^4.0.3
  path_provider: ^2.1.5
  hooks_riverpod: ^2.6.1
  flutter_smart_dialog: ^4.9.8+8
  hive_flutter: ^1.1.0
  flutter_widget_from_html_core: ^0.16.0
  flex_color_scheme: ^8.2.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0
  keyboard_actions: ^4.2.0
  fast_immutable_collections: ^11.0.4
  flutter_slidable: any
  loading_more_list_fast: ^7.2.3
  loading_more_list_library_fast: ^4.2.1
  dd_js_util: ^6.7.0
  dd_check_plugin: ^4.0.1
  permission_handler: ^12.0.0+1
  go_router: ^15.1.2
  responsive_builder: ^0.7.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  async: ^2.13.0
  share_plus: ^11.0.0
  blurrycontainer: ^2.1.0
  scoped_model: ^2.0.0
  animate_do: ^4.2.0


dev_dependencies:
  build_runner: ^2.4.15
  freezed: any
  json_serializable: any
  hive_generator_plus: ^4.0.2

dependency_overrides:

  flutter_lints: ^6.0.0
  web: ^1.1.1
  meta: ^1.17.0
  collection: ^1.19.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/nav/
    - assets/icons/
    - assets/svg/
    - assets/svg/user/
    - assets/svg/cate/
    - assets/json/
    - assets/images/waimai/hb/