name: demo1
description: 典典的小卖部,淘客版本 qq群667186542
version: 3.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.5"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  supercharged: ^2.1.1
  flutter_syntax_view: ^4.1.0
  date_format: ^2.0.7
  dio: ^5.6.0
  flutter_spinkit: ^5.2.1
  tab_indicator_styler: ^2.0.0
  fbutton_nullsafety: ^5.0.0
  fsuper_nullsafety: ^3.0.3
  common_utils: ^2.1.0
  extended_image: ^8.2.1
  waterfall_flow: ^3.0.3
  extended_list: ^3.0.2
  pull_to_refresh_notification: ^3.1.0
  connectivity_plus: ^6.0.5
  fsearch_nullsafety: ^2.0.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  extended_text: ^14.0.1
  animated_text_kit: ^4.2.2
  html: ^0.15.4
  extended_tabs: ^4.1.0
  after_layout: ^1.2.0
  palette_generator: ^0.3.3+4
  crypto: ^3.0.5
  encrypt: ^5.0.3
  extended_nested_scroll_view: ^6.2.1
  sliver_tools: ^0.2.12
  extended_sliver: ^2.1.3
  fcontrol_nullsafety: ^2.0.0
  get_it: ^7.7.0
  logger: ^2.4.0
  shelf_proxy: ^1.0.4
  bubble_tab_indicator: ^0.1.6
  badges: ^3.1.2
  carousel_pro_nullsafety: ^2.0.0
  flutter_markdown: ^0.7.3+1
  zefyrka: ^1.6.0
  package_info: ^2.0.2
  show_up_animation: ^2.0.0
  hive: ^2.2.3
  flutter_swiper_null_safety_flutter3: ^4.0.3
  path_provider: ^2.1.4
  hooks_riverpod: ^2.5.2
  flutter_smart_dialog: ^4.9.8
  hive_flutter: ^1.1.0
  flutter_widget_from_html_core: ^0.15.1
  flex_color_scheme: ^7.3.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.1
  keyboard_actions: ^4.2.0
  fast_immutable_collections: ^10.2.4
  flutter_slidable: ^3.1.1
  loading_more_list_fast: ^7.1.7
  loading_more_list_library_fast: ^4.1.5
  dd_js_util: ^6.3.2
  dd_check_plugin: ^3.2.1
  permission_handler: ^11.3.1
  go_router: ^14.2.6
  responsive_builder: ^0.7.1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  webview_flutter: ^4.8.0
  async: ^2.11.0
  share_plus: ^10.0.2
  blurrycontainer: ^2.1.0
  scoped_model: ^2.0.0
  animate_do: ^3.3.4

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  hive_generator_plus: ^3.0.4

dependency_overrides:
  watcher: ^1.1.0
  flutter_lints: ^4.0.0
  web: ^0.5.1
  meta: ^1.15.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/nav/
    - assets/icons/
    - assets/svg/
    - assets/svg/user/
    - assets/svg/cate/
    - assets/json/
    - assets/images/waimai/hb/